CREATE TABLE IF NOT EXISTS final_selections (
  id BIGSERIAL PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  photo_id BIGINT NOT NULL UNIQUE REFERENCES photos(id) ON DELETE CASCADE,
  selected_by VARCHAR(120) NOT NULL DEFAULT 'user',
  source VARCHAR(120) NOT NULL DEFAULT 'manual',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
